language: node_js

branches:
  only:
    - master
env:
  global:
    - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
node_js:
  - 12
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE `sabia-testing`;'
  - (cd packages/api && cp .env.example .env)
install:
  - npm install
  - npx lerna bootstrap
  - (cd packages/api && npm install)
script:
  - npm run lint
  - (cd packages/api && npm run coverage)
  - (cd packages/web && npm run test)
after_script:
  - (COVERALLS_FLAG_NAME=api cd packages/api && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls)
  - (COVERALLS_FLAG_NAME=web cd packages/web && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls)
